# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalculadoraCientifica.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(363, 490)
        self.pushButton_38 = QtWidgets.QPushButton(Dialog)
        self.pushButton_38.setGeometry(QtCore.QRect(220, 280, 61, 61))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_26 = QtWidgets.QPushButton(Dialog)
        self.pushButton_26.setGeometry(QtCore.QRect(10, 280, 61, 61))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setGeometry(QtCore.QRect(150, 280, 61, 61))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_31 = QtWidgets.QPushButton(Dialog)
        self.pushButton_31.setGeometry(QtCore.QRect(80, 140, 61, 61))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_37 = QtWidgets.QPushButton(Dialog)
        self.pushButton_37.setGeometry(QtCore.QRect(290, 280, 61, 61))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_32 = QtWidgets.QPushButton(Dialog)
        self.pushButton_32.setGeometry(QtCore.QRect(80, 280, 61, 61))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_25 = QtWidgets.QPushButton(Dialog)
        self.pushButton_25.setGeometry(QtCore.QRect(150, 350, 61, 61))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_28 = QtWidgets.QPushButton(Dialog)
        self.pushButton_28.setGeometry(QtCore.QRect(290, 420, 61, 61))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_23 = QtWidgets.QPushButton(Dialog)
        self.pushButton_23.setGeometry(QtCore.QRect(10, 420, 131, 61))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_36 = QtWidgets.QPushButton(Dialog)
        self.pushButton_36.setGeometry(QtCore.QRect(10, 140, 61, 61))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_34 = QtWidgets.QPushButton(Dialog)
        self.pushButton_34.setGeometry(QtCore.QRect(220, 350, 61, 61))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_21 = QtWidgets.QPushButton(Dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 210, 61, 61))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_33 = QtWidgets.QPushButton(Dialog)
        self.pushButton_33.setGeometry(QtCore.QRect(80, 210, 61, 61))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_27 = QtWidgets.QPushButton(Dialog)
        self.pushButton_27.setGeometry(QtCore.QRect(10, 350, 61, 61))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_20 = QtWidgets.QPushButton(Dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(150, 420, 61, 61))
        self.pushButton_20.setObjectName("pushButton_20")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_2.setGeometry(QtCore.QRect(40, -90, 271, 81))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.pushButton_29 = QtWidgets.QPushButton(Dialog)
        self.pushButton_29.setGeometry(QtCore.QRect(150, 210, 61, 61))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(Dialog)
        self.pushButton_30.setGeometry(QtCore.QRect(290, 350, 61, 61))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_24 = QtWidgets.QPushButton(Dialog)
        self.pushButton_24.setGeometry(QtCore.QRect(80, 350, 61, 61))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_35 = QtWidgets.QPushButton(Dialog)
        self.pushButton_35.setGeometry(QtCore.QRect(220, 210, 61, 61))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_39 = QtWidgets.QPushButton(Dialog)
        self.pushButton_39.setGeometry(QtCore.QRect(290, 140, 61, 61))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(Dialog)
        self.pushButton_40.setGeometry(QtCore.QRect(290, 210, 61, 61))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(Dialog)
        self.pushButton_41.setGeometry(QtCore.QRect(220, 140, 61, 61))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(Dialog)
        self.pushButton_42.setGeometry(QtCore.QRect(150, 140, 61, 61))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(Dialog)
        self.pushButton_43.setGeometry(QtCore.QRect(220, 420, 61, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setObjectName("pushButton_43")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 341, 101))
        font = QtGui.QFont()
        font.setFamily("Adobe Heiti Std R")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_38.setText(_translate("Dialog", "*"))
        self.pushButton_26.setText(_translate("Dialog", "4"))
        self.pushButton_22.setText(_translate("Dialog", "6"))
        self.pushButton_31.setText(_translate("Dialog", "DEL"))
        self.pushButton_37.setText(_translate("Dialog", "÷"))
        self.pushButton_32.setText(_translate("Dialog", "5"))
        self.pushButton_25.setText(_translate("Dialog", "3"))
        self.pushButton_28.setText(_translate("Dialog", "="))
        self.pushButton_23.setText(_translate("Dialog", "0"))
        self.pushButton_36.setText(_translate("Dialog", "C"))
        self.pushButton_34.setText(_translate("Dialog", "+"))
        self.pushButton_21.setText(_translate("Dialog", "7"))
        self.pushButton_33.setText(_translate("Dialog", "8"))
        self.pushButton_27.setText(_translate("Dialog", "1"))
        self.pushButton_20.setText(_translate("Dialog", ","))
        self.pushButton_29.setText(_translate("Dialog", "9"))
        self.pushButton_30.setText(_translate("Dialog", "-"))
        self.pushButton_24.setText(_translate("Dialog", "2"))
        self.pushButton_35.setText(_translate("Dialog", "√"))
        self.pushButton_39.setText(_translate("Dialog", "TAN"))
        self.pushButton_40.setText(_translate("Dialog", "x^"))
        self.pushButton_41.setText(_translate("Dialog", "COS"))
        self.pushButton_42.setText(_translate("Dialog", "SEN"))
        self.pushButton_43.setText(_translate("Dialog", "π"))

